tool_panel_section_label: Machine Learning
tools:
- name: ludwig_evaluate 
  owner: paulo_lyra_jr
- name: ludwig_experiment 
  owner: paulo_lyra_jr
- name: ludwig_hyperot 
  owner: paulo_lyra_jr
- name: ludwig_predict 
  owner: paulo_lyra_jr
- name: ludwig_renderconfig 
  owner: paulo_lyra_jr
- name: ludwig_train
  owner: paulo_lyra_jr
