tool_panel_section_label: Metabolomics
tools:
- name: msconvert
  owner: galaxyp
- name: msnbase_readmsdata
  owner: lecorguille
- name: xcms_fillpeaks
  owner: lecorguille
- name: xcms_group
  owner: lecorguille
- name: xcms_merge
  owner: lecorguille
- name: xcms_retcor
  owner: lecorguille
- name: xcms_xcmsset
  owner: lecorguille
- name: matchms
  owner: recetox
- name: matchms_filtering
  owner: recetox
- name: matchms_formatter
  owner: recetox
- name: ramclustr
  owner: recetox
- name: ramclustr_define_experiment
  owner: recetox
- name: riassigner
  owner: recetox
- name: waveica
  owner: recetox
