---
# This is the default galaxy.yml from galaxy/galaxy:19.05, the only modification is the logging config. Other changes
# should be done with GALAXY_CONFIG_*

uwsgi:
    buffer-size: 16384
    die-on-term: true
    enable-threads: true
    hook-master-start: unix_signal:2 gracefully_kill_them_all
    hook-master-start: unix_signal:15 gracefully_kill_them_all
    http: 0.0.0.0:8080
    master: true
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
    offload-threads: 2
    processes: 1
    py-call-osafterfork: true
    pythonpath: /galaxy/server/lib
    static-map: /static/style=/galaxy/server/static/style/blue
    static-map: /static=/galaxy/server/static
    threads: 4
    thunder-lock: true
    virtualenv: /galaxy/server/.venv

galaxy:
    builds_file_path: /galaxy/server/tool-data/shared/ucsc/builds.txt.sample
    citation_cache_data_dir: /galaxy/server/database/citations/data
    citation_cache_lock_dir: /galaxy/server/database/citations/locks
    data_manager_config_file: /galaxy/server/config/data_manager_conf.xml.sample
    database_connection: postgresql://galaxydbuser:42@gpsql/galaxy
    datatypes_config_file: /galaxy/server/config/datatypes_conf.xml.sample
    external_service_type_config_file: /galaxy/server/config/external_service_types_conf.xml.sample
    file_path: /galaxy/server/database/datasets
    integrated_tool_panel_config: /galaxy/server/config/integrated_tool_panel.xml
    job_working_directory: /galaxy/server/database/jobs
    migrated_tools_config: /galaxy/server/config/migrated_tools_conf.xml
    new_file_path: /galaxy/server/database/tmp
    object_store_cache_path: /galaxy/server/database/object_store_cache
    openid_config_file: /galaxy/server/config/openid_conf.xml.sample
    openid_consumer_cache_path: /galaxy/server/database/openid_consumer_cache
    shed_data_manager_config_file: /galaxy/server/config/shed_data_manager_conf.xml
    shed_tool_data_table_config: /galaxy/server/config/shed_tool_data_table_conf.xml
    template_cache_path: /galaxy/server/database/template_cache
    tool_config_file: /galaxy/server/config/tool_conf.xml.sample,/galaxy/server/config/shed_tool_conf.xml
    tool_data_table_config_path: /galaxy/server/config/tool_data_table_conf.xml.sample
    tool_dependency_dir: /galaxy/server/database/dependencies
    tool_sheds_config_file: /galaxy/server/config/tool_sheds_conf.xml.sample
    ucsc_build_sites: /galaxy/server/tool-data/shared/ucsc/ucsc_build_sites.txt.sample
    visualization_plugins_directory: config/plugins/visualizations
    whoosh_index_dir: /galaxy/server/database/whoosh_cache
    logging:
      disable_existing_loggers: false
      filters:
        stack:
          (): galaxy.web.stack.application_stack_log_filter
      formatters:
        stack:
          (): galaxy.web.stack.application_stack_log_formatter
      handlers:
        console:
          class: logging.StreamHandler
          filters:
          - stack
          formatter: stack
          level: DEBUG
          stream: ext://sys.stderr
      loggers:
        amqp:
          level: INFO
          qualname: amqp
        paste.httpserver.ThreadPool:
          level: WARN
          qualname: paste.httpserver.ThreadPool
        routes.middleware:
          level: WARN
          qualname: routes.middleware
      root:
        handlers:
        - console
        level: DEBUG
      version: 1
