name: Install and update IWC tools

on:
  schedule:
    # At 10:00 every day
    - cron: "0 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-repos:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolset: [usegalaxy.org, cloud]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Clone IWC repo
        run: git clone https://github.com/galaxyproject/iwc /tmp/iwc
      - name: Run update script
        run: python scripts/get_iwc_tools.py -w /tmp/iwc -s ${{ matrix.toolset }} -u uncategorized.yml
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Install IWC tools for ${{ matrix.toolset }} ${{ steps.date.outputs.date }}
            branch: iwc-update-${{ matrix.toolset }}
            branch-suffix: timestamp
